pipeline {
    agent any

    stages {
        stage('pull code') {
            steps {
               checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'Crazyorchid', url: 'https://github.com/Crazyorchid/SEP-CONT8-Server']]])
            }
        }
         stage('build project') {
            steps {
             sh 'mvn clean package'
            }
        }
        stage('deploy project') {
            steps {
             deploy adapters: [tomcat8(credentialsId: 'd9d0875c-1fd9-45c4-b7fa-e52d1e2becea', path: '', url: 'http://18.117.12.236:8080')], contextPath: null, war: 'target/*.war'
            }
        }
    }
}